import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock3, Menu, Moon, Search, Settings2, Sun, Volume2, X } from 'lucide-react'

type Hour = { id: string; label: string; latin: string; time: string; source: string }
const hours: Hour[] = [
  { id: 'matutinum', label: 'Office of Readings', latin: 'Matutinum', time: 'Before dawn', source: 'Ordinarium/Matutinum.txt' },
  { id: 'laudes', label: 'Lauds', latin: 'Laudes', time: 'Morning', source: 'Ordinarium/Laudes.txt' },
  { id: 'prima', label: 'Prime', latin: 'Prima', time: 'First hour', source: 'Ordinarium/Prima.txt' },
  { id: 'tertia', label: 'Terce', latin: 'Tertia', time: 'Mid-morning', source: 'Ordinarium/Minor.txt' },
  { id: 'sexta', label: 'Sext', latin: 'Sexta', time: 'Midday', source: 'Ordinarium/Minor.txt' },
  { id: 'nona', label: 'None', latin: 'Nona', time: 'Mid-afternoon', source: 'Ordinarium/Minor.txt' },
  { id: 'vespera', label: 'Vespers', latin: 'Vesperae', time: 'Evening', source: 'Ordinarium/Vespera.txt' },
  { id: 'completorium', label: 'Compline', latin: 'Completorium', time: 'Night', source: 'Ordinarium/Completorium.txt' },
]
const corpus = import.meta.glob('../data/latin/**/*.txt', { query: '?raw', import: 'default', eager: true }) as Record<string, string>
function currentHour() { const hour = new Date().getHours(); if (hour < 5) return hours[0]; if (hour < 9) return hours[1]; if (hour < 12) return hours[2]; if (hour < 15) return hours[4]; if (hour < 18) return hours[5]; if (hour < 21) return hours[6]; return hours[7] }
function readablePrayer(raw: string, fallback: string) { const lines = raw.split(/\r?\n/).filter((line) => line.trim() && !line.startsWith('!') && !line.startsWith('@') && !line.startsWith('&')); const blocks: { heading: string; text: string }[] = []; let heading = fallback; let text: string[] = []; const flush = () => { if (text.length) blocks.push({ heading, text: text.join(' ') }); text = [] }; lines.forEach((line) => { const section = line.match(/^\[(.+?)\]/); if (section) { flush(); heading = section[1].replace(/\s+\(.+\)/, ''); return } const clean = line.replace(/^\[.*?\]\s*/, '').replace(/;;\d+$/, '').trim(); if (clean) text.push(clean) }); flush(); return blocks.slice(0, 18) }

function App() {
  const [view, setView] = useState<'home' | 'prayer'>('home'); const [selected, setSelected] = useState<Hour>(currentHour()); const [drawer, setDrawer] = useState(false); const [dark, setDark] = useState(false); const [fontSize, setFontSize] = useState(18); const today = useMemo(() => new Date(), []); const dateKey = `${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`; const dateFile = corpus[`../data/latin/Sancti/${dateKey}.txt`] ?? corpus[`../data/latin/Martyrologium1960/${dateKey}.txt`]; const ordinary = corpus[`../data/latin/${selected.source}`] ?? ''; const source = [dateFile, ordinary].filter(Boolean).join('\n'); const prayer = readablePrayer(source, selected.latin)
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  const openHour = (hour: Hour) => { setSelected(hour); setView('prayer'); setDrawer(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="app-shell">
    <header className="site-header"><button className="brand" onClick={() => setView('home')} aria-label="Return to home"><span className="brand-mark">✦</span><span>breviary</span></button><div className="header-actions"><span className="date-chip"><CalendarDays size={15} /> {today.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}</span><button className="icon-button" onClick={() => setDrawer(true)} aria-label="Open menu"><Menu size={21} /></button></div></header>
    {view === 'home' ? <main className="home-page"><section className="hero"><div className="eyebrow"><span className="eyebrow-dot" /> 1962 edition · latin</div><h1>A quiet place<br /><em>to pray.</em></h1><p className="hero-copy">The daily office, carefully assembled for the rhythm of your day.</p><button className="primary-button" onClick={() => openHour(selected)}><BookOpen size={18} /> Pray {selected.label}<span className="button-arrow">→</span></button><div className="hero-note"><Clock3 size={15} /> It is time for <strong>{selected.label}</strong></div></section><section className="hours-section"><div className="section-heading"><div><span className="section-kicker">The daily office</span><h2>Today’s hours</h2></div><button className="text-button" onClick={() => setDrawer(true)}>View calendar <ChevronRight size={16} /></button></div><div className="hours-grid">{hours.map((hour, index) => <button className={`hour-card ${hour.id === selected.id ? 'active' : ''}`} key={hour.id} onClick={() => openHour(hour)}><span className="hour-number">0{index + 1}</span><span className="hour-latin">{hour.latin}</span><strong>{hour.label}</strong><span className="hour-time">{hour.time}</span></button>)}</div></section></main> : <main className="reader-page"><div className="reader-toolbar"><button className="back-button" onClick={() => setView('home')}><ChevronLeft size={17} /> All hours</button><span className="reader-date">{today.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</span><button className="icon-button" onClick={() => setDrawer(true)} aria-label="Open menu"><Settings2 size={19} /></button></div><article className="prayer-content" style={{ fontSize }}><span className="section-kicker">{selected.time} · {today.toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}</span><h1>{selected.label}</h1><p className="prayer-subtitle">{selected.latin}</p><div className="rule" />{prayer.length ? prayer.map((block, index) => <section className="prayer-block" key={`${block.heading}-${index}`}><h2>{block.heading}</h2><p>{block.text}</p></section>) : <p>Text for this office is being prepared.</p>}</article><div className="reader-footer"><button className="text-button" onClick={() => openHour(hours[Math.max(0, hours.indexOf(selected) - 1)])}><ChevronLeft size={16} /> Previous hour</button><button className="audio-button"><Volume2 size={16} /> Listen</button><button className="text-button" onClick={() => openHour(hours[Math.min(hours.length - 1, hours.indexOf(selected) + 1)])}>Next hour <ChevronRight size={16} /></button></div></main>}
    {drawer && <><div className="drawer-backdrop" onClick={() => setDrawer(false)} /><aside className="drawer"><div className="drawer-top"><span className="section-kicker">Navigate</span><button className="icon-button" onClick={() => setDrawer(false)} aria-label="Close menu"><X size={20} /></button></div><h2>Find your office.</h2><div className="drawer-search"><Search size={17} /><span>Search the breviary</span></div><nav className="drawer-nav"><span className="nav-label">Today</span>{hours.map((hour) => <button key={hour.id} onClick={() => openHour(hour)} className={selected.id === hour.id && view === 'prayer' ? 'current' : ''}><span>{hour.label}</span><small>{hour.latin}</small></button>)}<span className="nav-label">Explore</span><button><CalendarDays size={16} /> Liturgical calendar</button><button><BookOpen size={16} /> Proper & common</button></nav><div className="drawer-settings"><span className="nav-label">Settings</span><button onClick={() => setDark(!dark)}>{dark ? <Moon size={16} /> : <Sun size={16} />} {dark ? 'Dark theme' : 'Light theme'}<span className="setting-state">On</span></button><label><span>Text size</span><input type="range" min="16" max="24" value={fontSize} onChange={(event) => setFontSize(Number(event.target.value))} /></label></div></aside></>}
  </div>
}
export default App