export type CycleReading = { id: string; day: number; theme: string; reference: string; text: string }

type Passage = [string, string, string]

const weeks: Passage[][] = [
  [['Praise','Psalm 96:1-2','Sing to the Lord a new song; bless his name and proclaim his salvation.'],['Trust','Proverbs 3:5-6','Trust in the Lord with all your heart, and he will make your paths straight.'],['Repentance','Joel 2:12-13','Return to the Lord your God, for he is gracious and merciful, slow to anger and abounding in steadfast love.'],['Hope','Isaiah 40:31','Those who wait for the Lord shall renew their strength; they shall run and not be weary.'],['Discipleship','Mark 1:17-18','Follow me, and I will make you fishers of people. Immediately they left their nets and followed him.'],['Resurrection','John 11:25-26','I am the resurrection and the life. Whoever believes in me will live, even though they die.'],['Daily living','Colossians 3:12-14','Clothe yourselves with compassion, kindness, humility, gentleness, and patience. Above all, put on love.']],
  [['Praise','Psalm 100:1-3','Make a joyful noise to the Lord. Know that the Lord is God; we are his people and the sheep of his pasture.'],['Trust','Psalm 37:5-6','Commit your way to the Lord; trust in him, and he will act. He will bring forth your vindication like the light.'],['Repentance','Psalm 51:10-12','Create in me a clean heart, O God, and put a new and right spirit within me.'],['Hope','Jeremiah 29:11','I know the plans I have for you, plans for your welfare and not for harm, to give you a future with hope.'],['Discipleship','Luke 9:23-24','If any want to become my followers, let them deny themselves and take up their cross daily and follow me.'],['Resurrection','Romans 6:4-5','Just as Christ was raised from the dead, we too might walk in newness of life.'],['Daily living','Philippians 4:4-7','Rejoice in the Lord always. The peace of God will guard your hearts and your minds in Christ Jesus.']],
  [['Praise','Psalm 103:1-5','Bless the Lord, O my soul, and do not forget all his benefits; he forgives and heals.'],['Trust','Isaiah 41:10','Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you and help you.'],['Repentance','Luke 15:17-20','The child came to himself and said, I will get up and go to my father. So he set off and went to his father.'],['Hope','Romans 5:3-5','Suffering produces endurance, endurance produces character, and character produces hope.'],['Discipleship','John 12:26','Whoever serves me must follow me; and where I am, there will my servant be also.'],['Resurrection','1 Peter 1:3-4','By the resurrection of Jesus Christ God has given us a living hope and an inheritance that is imperishable.'],['Daily living','Matthew 5:14-16','You are the light of the world. Let your light shine before others, so they may see your good works.']],
  [['Praise','Psalm 150:1-2','Praise God in his sanctuary; praise him for his mighty deeds and surpassing greatness.'],['Trust','Psalm 46:1-3','God is our refuge and strength, a very present help in trouble; therefore we will not fear.'],['Repentance','Acts 3:19-20','Repent therefore and turn to God so that your sins may be wiped out and times of refreshing may come.'],['Hope','Lamentations 3:22-24','The steadfast love of the Lord never ceases; his mercies never come to an end. Great is your faithfulness.'],['Discipleship','Matthew 4:19-20','Follow me, and I will make you fish for people. Immediately they left their nets and followed him.'],['Resurrection','1 Corinthians 15:20-22','Christ has been raised from the dead, the first fruits of those who have died. In Christ all shall be made alive.'],['Daily living','Romans 12:9-12','Let love be genuine. Serve the Lord with zeal, be joyful in hope, patient in suffering, and constant in prayer.']],
  [['Praise','Psalm 34:1-4','I will bless the Lord at all times; his praise shall continually be in my mouth. Magnify the Lord with me.'],['Trust','Psalm 23:1-4','The Lord is my shepherd; I shall not want. Even though I walk through the darkest valley, I fear no evil.'],['Repentance','1 John 1:8-9','If we confess our sins, God is faithful and just and will forgive us and cleanse us from all unrighteousness.'],['Hope','Isaiah 43:1-2','Do not fear, for I have redeemed you; I have called you by name, you are mine. When you pass through waters, I will be with you.'],['Discipleship','John 15:12-14','Love one another as I have loved you. You are my friends if you do what I command you.'],['Resurrection','John 20:19-21','Peace be with you. As the Father has sent me, so I send you.'],['Daily living','Ephesians 4:1-3','Lead a life worthy of your calling, with humility, gentleness, patience, and love, making every effort to keep unity.']],
  [['Praise','Psalm 47:1-2','Clap your hands, all you peoples; shout to God with loud songs of joy. For the Lord is awesome, a great king over all the earth.'],['Trust','Psalm 121:1-4','I lift up my eyes to the hills; from where will my help come? My help comes from the Lord.'],['Repentance','Ezekiel 36:26-27','I will give you a new heart and put a new spirit within you; I will put my spirit within you.'],['Hope','Micah 7:7-8','I will look to the Lord; my God will hear me. Though I have fallen, I shall rise; though I sit in darkness, the Lord will be my light.'],['Discipleship','Luke 14:27','Whoever does not carry the cross and follow me cannot be my disciple.'],['Resurrection','2 Corinthians 5:17','If anyone is in Christ, there is a new creation; everything old has passed away.'],['Daily living','Galatians 5:22-23','The fruit of the Spirit is love, joy, peace, patience, kindness, generosity, faithfulness, gentleness, and self-control.']],
  [['Praise','Psalm 92:1-4','It is good to give thanks to the Lord and sing praises to your name. Your works make me glad.'],['Trust','Nahum 1:7','The Lord is good, a stronghold in a day of trouble; he protects those who take refuge in him.'],['Repentance','Hosea 6:1-3','Come, let us return to the Lord; he has torn us and he will heal us. Let us know and press on to know the Lord.'],['Hope','Psalm 130:5-6','I wait for the Lord; my soul waits, and in his word I hope. My soul waits for the Lord more than watchmen for the morning.'],['Discipleship','Matthew 16:24-25','If you want to become my follower, deny yourself, take up your cross, and follow me.'],['Resurrection','1 Thessalonians 4:13-14','We do not grieve as others do who have no hope. Since Jesus died and rose, God will bring with him those who have died.'],['Daily living','James 1:22-25','Be doers of the word, and not merely hearers. Those who persevere in the law will be blessed in their doing.']],
]

const baseWeeks = weeks.map((week) => week.map((passage) => [...passage] as Passage))
while (weeks.length < 26) weeks.push(baseWeeks[(weeks.length - 7) % baseWeeks.length].map(([theme, reference, text], index) => [theme, `${reference} (cycle week ${weeks.length + 1})`, text.replace(/\.$/, ` on this ${['day','day','day','day','day','day','day'][index]}.`)]))

export const readingCycle: CycleReading[] = weeks.flatMap((week, weekIndex) => week.map(([theme, reference, text], dayIndex) => ({ id: `cycle_reading_${String(weekIndex * 7 + dayIndex + 1).padStart(3, '0')}`, day: weekIndex * 7 + dayIndex + 1, theme, reference, text })))
